In [1]:
import pandas as pd

df_skaters = pd.read_csv("speed_skaters.csv")
df_skaters.head()

                    Name  Birth year  Height  Weight
0  Aerchenghazi XIAKAINI        1995    1.85      83
1      Aleksandr LEBEDEV        1987    1.78      70
2       Aleksandr ZHIGIN        1986    1.80      80
3        Aleksey SUVOROV        1991    1.80      80
4          Aleksey YESIN        1987    1.78      85

In [2]:
df1 = pd.read_csv("mens1500_2006.csv")
df2 = pd.read_csv("mens1500_2010.csv")
df3 = pd.read_csv("mens1500_2014.csv")
df4 = pd.read_csv("mens1500_2018.csv")

In [7]:
df_combined = pd.concat([df1,df2,df3,df4])
df = pd.merge(df_skaters, df_combined, left_on="Name",right_on="Athlete",how="inner").drop(["Athlete"],axis=1)
df.head()

,Name,Birth year,Height,Weight,Rank,Country,Result,Finished,Year
0,Aerchenghazi XIAKAINI,1995,1.85,83,32.0,CHN,01:50.16,1,2018
1,Aleksandr LEBEDEV,1987,1.78,70,36.0,RUS,01:52.09,1,2010
2,Aleksandr ZHIGIN,1986,1.80,80,34.0,KAZ,01:49.48,1,2014
3,Aleksey SUVOROV,1991,1.80,80,25.0,RUS,01:48.11,1,2014
4,Aleksey YESIN,1987,1.78,85,21.0,RUS,01:48.65,1,2010

In [4]:
df[(df["Height"] > 1.80) & (df["Weight"] > 80)]

,Name,Birth year,Height,Weight,Rank,Country,Result,Finished,Year
0,Aerchenghazi XIAKAINI,1995,1.85,83,32.0,CHN,01:50.16,1,2018
11,Benjamin DONNELLY,1996,1.90,82,31.0,CAN,01:49.68,1,2018
18,Christoffer Fagerli RUKKE,1988,1.90,89,20.0,NOR,01:48.62,1,2010
19,Daniel FRIBERG,1986,1.83,83,25.0,SWE,01:49.13,1,2010
24,Denis YUSKOV,1989,1.90,84,4.0,RUS,01:45.37,1,2014
25,Denny MORRISON,1985,1.83,81,11.0,CAN,01:48.04,1,2006
26,Denny MORRISON,1985,1.83,81,9.0,CAN,01:46.93,1,2010
27,Denny MORRISON,1985,1.83,81,3.0,CAN,01:45.22,1,2014
28,Denny MORRISON,1985,1.83,81,13.0,CAN,01:46.36,1,2018
33,Matteo ANESI,1984,1.85,81,29.0,ITA,01:49.88,1,2006
34,Matteo ANESI,1984,1.85,81,12.0,ITA,01:47.34,1,2010
35,Matteo ANESI,1984,1.85,81,39.0,ITA,01:50.59,1,2014
37,Jan BLOKHUIJSEN,1989,1.84,81,13.0,NED,01:46.50,1,2014
39,Zbigniew BRODKA,1984,1.83,85,27.0,POL,01:49.45,1,2010
40,Zbigniew BRODKA,1984,1.83,85,1.0,POL,01:45.01,1,2014
41,Zbigniew BRODKA,1984,1.83,85,12.0,POL,01:46.31,1,2018
45,Shani DAVIS,1982,1.88,86,2.0,USA,01:46.13,1,2006
46,Shani DAVIS,1982,1.88,86,2.0,USA,01:46.10,1,2010
47,Shani DAVIS,1982,1.88,86,11.0,USA,01:45.98,1,2014
48,Shani DAVIS,1982,1.88,86,19.0,USA,01:46.74,1,2018
49,Vincent DE HAITRE,1994,1.82,86,33.0,CAN,01:49.42,1,2014
50,Vincent DE HAITRE,1994,1.82,86,21.0,CAN,01:47.32,1,2018
52,Joel ERIKSSON,1984,1.89,88,24.0,SWE,01:49.08,1,2010
62,Sindre HENRIKSEN,1992,1.90,82,7.0,NOR,01:45.64,1,2018
63,Fredrik van der HORST,1989,1.88,84,29.0,NOR,01:49.58,1,2010
72,Simon KUIPERS,1982,1.86,86,4.0,NED,01:46.58,1,2006
73,Simon KUIPERS,1982,1.86,86,7.0,NED,01:46.76,1,2010
74,Yevgeny LALENKOV,1981,1.88,85,23.0,RUS,01:49.00,1,2006
75,Yevgeny LALENKOV,1981,1.88,85,11.0,RUS,01:47.06,1,2010
81,Havard LORENTZEN,1992,1.87,86,16.0,NOR,01:47.27,1,2014
91,Konrad NAGY,1992,1.88,82,26.0,HUN,01:48.12,1,2014
92,Konrad NAGY,1992,1.88,82,29.0,HUN,01:49.01,1,2018
99,Kjeld NUIS,1989,1.86,87,1.0,NED,01:44.01,1,2018
101,Kyle PARROTT,1985,1.85,86,37.0,CAN,01:52.67,1,2010
105,Johan RÖJLER,1981,1.83,82,33.0,SWE,01:50.50,1,2006
106,Johan RÖJLER,1981,1.83,82,28.0,SWE,01:49.50,1,2010
107,Samuel SCHWARZ,1983,1.84,90,32.0,GER,01:50.07,1,2010
110,Ivan SKOBREV,1983,1.87,85,6.0,RUS,01:46.91,1,2006
111,Ivan SKOBREV,1983,1.87,85,4.0,RUS,01:46.42,1,2010
112,Ivan SKOBREV,1983,1.87,85,18.0,RUS,01:47.62,1,2014
116,Longjiang SUN,1992,1.94,85,35.0,CHN,01:51.30,1,2010
120,Guojun TIAN,1990,1.88,84,21.0,CHN,01:47.95,1,2014
121,Sergey TROFIMOV,1995,1.84,81,18.0,OAR,01:46.69,1,2018
122,Mark TUITERT,1980,1.82,83,1.0,NED,01:45.57,1,2010
123,Mark TUITERT,1980,1.82,83,5.0,NED,01:45.42,1,2014
124,Koen VERWEIJ,1990,1.82,83,2.0,NED,01:45.01,1,2014
125,Koen VERWEIJ,1990,1.82,83,11.0,NED,01:46.26,1,2018
131,Jan BOS,1975,1.90,85,20.0,NED,01:48.61,1,2006
134,Arne DANKERS,1980,1.88,82,17.0,CAN,01:48.42,1,2006
135,Stefano DONAGRANDI,1976,1.85,84,22.0,ITA,01:48.85,1,2006
136,Steven ELM,1975,1.85,81,12.0,CAN,01:48.09,1,2006
139,Aleksandr KIBALKO,1973,1.83,87,32.0,RUS,01:50.29,1,2006
142,Joon MOON,1982,1.85,85,16.0,KOR,01:48.38,1,2006
145,Risto ROSENDAHL,1979,1.88,88,24.0,FIN,01:49.51,1,2006
152,Even WETTEN,1982,1.88,88,10.0,NOR,01:47.78,1,2006

In [5]:
df_birth_year = df.groupby("Birth year")
mean_weight = df_birth_year["Weight"].mean()
mean_weight

Birth year
1970    64.000000
1973    82.000000
1974    70.000000
1975    82.000000
1976    79.500000
1977    77.000000
1978    83.000000
1979    77.666667
1980    79.600000
1981    80.181818
1982    82.583333
1983    82.714286
1984    82.888889
1985    77.785714
1986    77.538462
1987    78.000000
1988    82.250000
1989    78.785714
1990    79.250000
1991    72.166667
1992    79.750000
1993    71.250000
1994    80.000000
1995    77.250000
1996    78.000000
1997    65.000000
1998    80.000000
1999    68.000000
Name: Weight, dtype: float64